server {
    listen 80 default_server;
    listen [::]:80 default_server;
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name rtsp.vishvajeetshukla.in;

    ssl_certificate /etc/ssl/rtsp/origin.crt;
    ssl_certificate_key /etc/ssl/rtsp/origin.key;

    root /var/www/rtsp-viewer;
    index index.html;
    client_max_body_size 2m;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /vendor/ {
        try_files $uri =404;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location /assets/ {
        try_files $uri =404;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}

server {
    listen 80;
    listen [::]:80;
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name rtsp-api.vishvajeetshukla.in;

    ssl_certificate /etc/ssl/rtsp/origin.crt;
    ssl_certificate_key /etc/ssl/rtsp/origin.key;

    client_max_body_size 2m;

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 75s;
        proxy_buffering off;
    }
}
